### ISSUE TITLE
Crash report 1.12

### ISSUE THREAD

**Issue by PurpleHel** [elytra/LingeringLoot#4]
First crash happened while exploring. After that, crashes every time I open the world until I disable lingering loot and open the world once. Then I can re-enable lingering loot and reopen the world and it'll be fine...til the next time. The paste has the mods list, except for lingering loot which was disabled when I copied the list. It's lingering loot 1.12-4.2. Single player world.

https://pastebin.com/rtqhxWUG

**Comment by alexbobp** [comment]
Thanks, you're the second person to report this issue.  Would you be willing to provide me with a world, when it's in the state where the issue occurs?  That would make it very easy for me to hunt down this issue in a debugger, which I must admit is baffling me right now from just being able to read my code and guess.

Sorry for the inconvenience, but I'll really appreciate it if you can help me!  The previous person who reported it was reporting it on behalf of a friend and couldn't get me a test case.

I've set up a file dropoff if it helps: https://testificate.xen.prgmr.com/drop/  If you can include both the world and the mods folder that would be great.  (It will give you a non-working url at the end, you can ignore that or give it to me)

**Comment by alexbobp** [comment]
btw, duplicates #3.  I think issue mentions are the closest github has to linking issues

**Comment by PurpleHel** [comment]
Checking if I fixed it in my world or not. If I did, I'll happily share next time it happens. Otherwise I'll upload the minecraft folder shortly. I'll let you know either way. I use multimc, so sharing the world is easy.

**Comment by PurpleHel** [comment]
Good news! I hadn't fixed my world yet, so I'll upload it. If you do launch offline in multimc, and put your offline username as PurpleHel it should sign you into my char.

**Comment by PurpleHel** [comment]
File size is 335mb tho (LOTS of mods), so I uploaded to my google drive and am sending you the link via pm. In case you're unfamiliar with multimc, get it from https://multimc.org/, use the development version, go to add instance, and then there's an import modpack option, point it at the zip file, and it'll recreate my setup exactly. It includes config, so you may wanna delete my options.txt, cos I set my keymap up weird. :)

**Comment by PurpleHel** [comment]
lol, can't find pm on github. sent link as a text file to your file uploader. https://testificate.xen.prgmr.com/drop/i16quprt.txt

**Comment by PurpleHel** [comment]
d'oh. there's two worlds in the zip. The crash is in the world named Space.

**Comment by alexbobp** [comment]
Got it, thanks!  no worries about the link, I should have set a higher limit...

**Comment by PurpleHel** [comment]
Oh, and switching to lingering loot 3.1 from 4.2 also solves the crash.

**Comment by alexbobp** [comment]
Ok thanks for that tip, I looked at what I changed in that part of the code between 3.1 and 4.2 and I have a suspicion now.  (There were major overhauls, but luckily not to the bit in question)  I'm glad I marked the 4.x releases as betas so far.  The next one will definitely also be a beta, because it will have this fix, another bugfix, and more under the hood changes that hopefully nobody notices.  Were you relying on any 4.x features?

**Comment by PurpleHel** [comment]
I don't think so. I didn't even notice what was new in v4. :) I mostly just use lingering loot cos it makes me so mad when I miss drops cos I'm still fighting off mobs. So I have most drops set to half an hour and anything dropped by the player set to 7 days, in case I drop an expensive tool and don't notice.

**Comment by alexbobp** [comment]
Ok, I literally can't make my computer run your modpack!  I can probably try to reproduce later with a stripped down version, but I have to go to bed for now, so if you want something to try, the build at https://ci.elytradev.com/job/elytra/job/LingeringLoot/job/master/50/ has a fix to my best guess at what the problem is.  (It also has other changes I've been working on but hopefully that has no impact on you)

The only difference between builds 49 ( https://ci.elytradev.com/job/elytra/job/LingeringLoot/job/master/49/ ) and 50 is that fix.  If I'm right about what the issue is, 49 should crash but 50 won't.

There's honestly a pretty good chance nothing in lingering loot 4.x affects you :P  It was mainly an overhaul of the mod's configurability.  It has some neat possibilities that you might not care about for your use cases, but if you want to see the new stuff look in lingeringloot.rules instead of lingeringloot.cfg.  (There are more updates, so if you try the build from CI, you might want to delete lingeringloot.rules so it regenerates with the latest documentation)

If you can confirm this fix works, I'll put it out as a new beta version.

**Comment by PurpleHel** [comment]
Minecraft crashes on launch with version 50.

**Comment by alexbobp** [comment]
Damn, sorry.  Can you give me the stacktrace?

**Comment by alexbobp** [comment]
(is it the exact same error?  I just want to make sure)

**Comment by alexbobp** [comment]
Ok, I tried something slightly more paranoid.  If this doesn't work, I'm definitely totally missing the point about what this bug is.
https://ci.elytradev.com/job/elytra/job/LingeringLoot/job/master/51/

**Comment by PurpleHel** [comment]
....I can't believe I forgot the crash report. *le sigh* Trying 51.

**Comment by PurpleHel** [comment]
51 looks like it works!

**Comment by alexbobp** [comment]
Ok, awesome!  Thanks, I'll mark this as closed, and expect an update on curseforge soon (which will be identical to that build 51 but with a version bump)

**Comment by alexbobp** [comment]
And no need to sigh at yourself... you were extremely helpful.  I hate to have to ask a user to blindly test my builds for me.
